### ISSUE TITLE
Kategorie IDs im Frontend

### ISSUE THREAD

**Issue by eiswurm** [terminal42/contao-calendar-categories#3]
Ist ist möglich die Kategorie-IDs im Frontend auszugeben? Bei den Variablen z.B. beim event_full.html5 ist nichts dabei.

**Comment by aschempp** [comment]
in 11c2b03bfa802955d996f0ea9fb3b3290cfd98ad hinzugefügt. Im `event_full` Template (etc.) sollten die IDs der Kategorien ab Version 1.1.1 als `$this->categories` verfügbar sein.

**Comment by eiswurm** [comment]
Bei mir zeigt es sie leider immer noch nicht an, weder im event_full noch in den anderen (upcoming etc.).

**Comment by aschempp** [comment]
du müsstest das Template anpassen und sie selber ausgeben, automatisch passiert nichts...

**Comment by fritzmg** [comment]
Die Änderung greift nur, wenn die Filterung aktiv ist.

**Comment by fritzmg** [comment]
This is how you could do it in your own hook:

```php
namespace App\EventListener\GetAllEvents;

use Codefog\HasteBundle\Model\DcaRelationsModel;
use Contao\CoreBundle\DependencyInjection\Attribute\AsHook;
use Terminal42\CalendarCategoriesBundle\Model\CalendarCategoryModel;

#[AsHook('getAllEvents')]
class EventTitlesListener
{
    public function __invoke(array $days): array
    {
        foreach ($days as &$dates) {
            foreach ($dates as &$events) {
                foreach ($events as &$event) {
                    $categoryIds = DcaRelationsModel::getRelatedValues('tl_calendar_events', 'categories', $event['id']);
                    $event['categoriesCollection'] = CalendarCategoryModel::findMultipleByIds($categoryIds);
                }
            }
        }

        return $days;
    }
}
```
```php
<!-- templates/event_teaser.html5 -->
<?php foreach ($this->categoriesCollection ?? [] as $category): ?>
  <div><?= $category->name ?></div>
<?php endforeach; ?>
```

**Comment by marcelj-isystem** [comment]
Hi! I'm writing to this issue, since it is very much also my use case - I want to display event category label within `Event Reader` module. It looks like event category information is not available in this module. I've managed to retrieve them by querying the DB within template, but I would rather solve this on module level where data is being compiled. 

```php
// Retrieve category details for given event ID
$categoryData = Database::getInstance()->prepare(
  'SELECT c.name FROM tl_calendar_category c INNER JOIN tl_calendar_events_categories ec ON ec.category_id = c.id WHERE ec.event_id = ?'
)->execute($this->id)->fetchAssoc();
```

I've tried to use `getAllEvents` hook as @fritzmg suggested, while it works for event list, Event Reader does not use this hook at all. Can you recommend me proper way to solve this?

Using Contao version **5.3.47**

Thanks for this extension and for possible answer!
